import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 12,
    gap: 10,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "800",
    color: "#000",
    letterSpacing: -0.5,
  },
  headerSub: {
    fontSize: 13,
    color: "#6B7280",
    marginTop: 3,
  },
  addBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#DCFCE7",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 7,
    gap: 4,
  },
  addBtnText: { fontWeight: "700", color: "#16A34A", fontSize: 14 },
  memberListHeader: {
    color: "#A0A0A0",
    fontSize: 13,
    fontWeight: "bold",
    marginLeft: 16,
    marginTop: 12,
    marginBottom: 8,
    letterSpacing: 0.5,
  },
  userList: { paddingHorizontal: 12 },
  userCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 14,
    marginBottom: 12,
    elevation: 1,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  avatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
  },
  avatarText: { fontWeight: "bold", fontSize: 18, color: "#fff" },
  userName: { fontWeight: "bold", fontSize: 16, color: "#111" },
  userUsername: { color: "#6B7280", fontSize: 12, marginTop: 5 },
  userEmail: { color: "#9CA3AF", fontSize: 13, marginTop: 1 },
  roleRow: { flexDirection: "row", alignItems: "center", marginTop: 10 },
  roleBadge: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
  },
  roleBadgeText: { fontSize: 13, fontWeight: "600" },
  adminBadge: { backgroundColor: "#FFF3CD" },
  adminBadgeText: { color: "#B8860B" },
  userBadge: { backgroundColor: "#DBEAFE" },
  userBadgeText: { color: "#1D4ED8" },
  selfBadge: {
    backgroundColor: "#DCFCE7",
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  selfBadgeText: { color: "#16A34A", fontWeight: "600", fontSize: 14 },
  actionCol: { flexDirection: "row", gap: 8, alignItems: "center" },
  editBtn: {
    backgroundColor: "#60A5FA",
    borderRadius: 10,
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
  },
  deleteBtn: {
    backgroundColor: "#F87171",
    borderRadius: 10,
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
  },

  // Permissions table
  permissionTable: {
    backgroundColor: "#fff",
    borderRadius: 16,
    margin: 12,
    marginTop: 4,
    padding: 16,
    elevation: 1,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  permissionTitle: { fontWeight: "800", fontSize: 17, marginBottom: 16, color: "#111" },
  permissionHeaderRow: { flexDirection: "row", alignItems: "center", paddingBottom: 8 },
  permissionFeatureCell: { flex: 1, fontSize: 14, color: "#9CA3AF", fontWeight: "600" },
  permissionAdminHeader: { width: 60, textAlign: "center", fontSize: 14, fontWeight: "700", color: "#16A34A" },
  permissionUserHeader: { width: 60, textAlign: "center", fontSize: 14, fontWeight: "700", color: "#2563EB" },
  permissionDivider: { height: 1, backgroundColor: "#F3F4F6", marginBottom: 4 },
  permissionRow: { flexDirection: "row", alignItems: "center", paddingVertical: 12 },
  permissionRowBorder: { borderBottomWidth: 1, borderBottomColor: "#F3F4F6" },
  permissionLabel: { flex: 1, fontSize: 15, color: "#6B7280" },
  permissionIconCell: { width: 60, alignItems: "center", justifyContent: "center" },

  // Modal
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  modalCard: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 24,
    width: "100%",
    maxWidth: 420,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  modalTitle: { fontSize: 18, fontWeight: "800", color: "#111" },
  inputLabel: { fontSize: 13, fontWeight: "600", color: "#6B7280", marginBottom: 6, marginTop: 12 },
  input: {
    backgroundColor: "#F9FAFB",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 11,
    fontSize: 15,
    color: "#111",
  },
  roleToggleRow: { flexDirection: "row", gap: 10, marginTop: 4 },
  roleToggleBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: "#E5E7EB",
    alignItems: "center",
    backgroundColor: "#F9FAFB",
  },
  roleToggleBtnActive: { borderColor: "#2563EB", backgroundColor: "#EFF6FF" },
  roleToggleBtnAdminActive: { borderColor: "#B8860B", backgroundColor: "#FFFBEB" },
  roleToggleTxt: { fontSize: 14, fontWeight: "600", color: "#9CA3AF" },
  roleToggleTxtActive: { color: "#1D4ED8" },
  roleToggleTxtAdminActive: { color: "#B8860B" },
  modalFooter: {
    flexDirection: "row",
    gap: 10,
    marginTop: 24,
  },
  cancelBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: "#E5E7EB",
    alignItems: "center",
  },
  cancelBtnText: { fontSize: 15, fontWeight: "600", color: "#6B7280" },
  saveBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: "#16A34A",
    alignItems: "center",
  },
  saveBtnText: { fontSize: 15, fontWeight: "700", color: "#fff" },
});
